import React, { useState, useEffect } from 'react';
import { useTelemetry } from '../context/TelemetryContext';
import { api } from '../services/api';
import { Recommendation } from '../types/telemetry';
import {
  LifeBuoy,
  ShieldCheck,
  Play,
  ArrowRight,
  Sliders,
  CheckCircle2,
  AlertTriangle,
  Flame,
  Battery,
  Radio,
  Rocket
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const RecommendationsPage: React.FC = () => {
  const { telemetry } = useTelemetry();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    api.getRecommendations()
      .then((data) => {
        setRecommendations(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [telemetry?.operating_mode, telemetry?.temperature]);

  const handleSimulateAction = (rec: Recommendation) => {
    navigate('/mission-control/simulation', {
      state: { prefill: rec.simulation_parameters, title: rec.title }
    });
  };

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'HIGH':
        return 'bg-rose-950 text-rose-300 border-rose-800 animate-pulse';
      case 'MEDIUM':
        return 'bg-amber-950 text-amber-300 border-amber-800';
      default:
        return 'bg-emerald-950 text-emerald-300 border-emerald-800';
    }
  };

  return (
    <div className="space-y-5">
      {/* Title Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#16243f] pb-3">
        <div>
          <h1 className="text-xl font-bold font-mono text-slate-100 flex items-center gap-2">
            <LifeBuoy className="w-5 h-5 text-cyan-400" />
            OPERATIONAL RECOMMENDATIONS & ACTION PLANS
          </h1>
          <p className="text-xs text-slate-400 font-mono">
            AI and rule-based mitigation strategies engineered to avert predicted subsystem failures and restore nominal margin.
          </p>
        </div>

        <div className="text-xs font-mono text-slate-400 bg-[#071328] px-3 py-1 rounded border border-[#16243f]">
          ACTIONS AVAILABLE: <span className="text-cyan-300 font-bold">{recommendations.length}</span>
        </div>
      </div>

      {/* Safety Notice */}
      <div className="p-3 rounded bg-[#0a1628] border border-cyan-900/60 flex items-center gap-3 text-xs font-mono text-cyan-300">
        <ShieldCheck className="w-5 h-5 text-cyan-400 shrink-0" />
        <div>
          <strong>Safety & Operational Protocol:</strong> Recommendations generated by ORBITAL TWIN are intended for engineering simulation and verification. Actions are validated through counterfactual simulation before ground commands are formulated.
        </div>
      </div>

      {/* Recommendation Action Cards Feed */}
      <div className="space-y-4">
        {recommendations.map((rec) => {
          const isHigh = rec.priority === 'HIGH';
          return (
            <div
              key={rec.id}
              className={`aerospace-panel p-5 rounded border transition-all ${
                isHigh ? 'border-amber-500/60 bg-amber-950/15' : 'border-[#16243f]'
              }`}
            >
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                <div className="space-y-2 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono text-xs text-slate-400 font-bold">{rec.id}</span>
                    <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800/40">
                      {rec.subsystem.toUpperCase()} SUBSYSTEM
                    </span>
                    <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${getPriorityBadge(rec.priority)}`}>
                      {rec.priority} PRIORITY
                    </span>
                  </div>

                  <h3 className="text-base font-bold font-mono text-slate-100">{rec.title}</h3>
                  <p className="text-xs text-slate-300 leading-relaxed font-sans">{rec.description}</p>

                  <div className="p-2.5 rounded bg-[#071120] border border-[#14233e] text-xs font-mono text-emerald-400 flex items-center gap-1.5 mt-2">
                    <CheckCircle2 className="w-4 h-4 shrink-0" />
                    <span><strong>Projected Outcome:</strong> {rec.simulated_effect}</span>
                  </div>
                </div>

                {/* Simulate Action Button */}
                <div className="shrink-0 flex flex-col justify-center items-end border-t md:border-t-0 border-[#16243f] pt-3 md:pt-0">
                  <button
                    onClick={() => handleSimulateAction(rec)}
                    className="px-4 py-2.5 rounded bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-mono font-bold tracking-wider uppercase flex items-center gap-2 transition-all shadow-md shadow-cyan-950"
                  >
                    <Sliders className="w-4 h-4" />
                    SIMULATE ACTION
                  </button>
                  <span className="text-[10px] font-mono text-slate-500 mt-1">
                    Loads into What-If Simulator
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
