import React, { useState, useEffect } from 'react';
import { useTelemetry } from '../context/TelemetryContext';
import { api } from '../services/api';
import { Recommendation } from '../types/telemetry';
import {
  LifeBuoy,
  ShieldCheck,
  Play,
  ArrowRight,
  Sliders,
  CheckCircle2,
  AlertTriangle,
  Flame,
  Battery,
  Radio,
  Rocket
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const RecommendationsPage: React.FC = () => {
  const { telemetry } = useTelemetry();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    api.getRecommendations()
      .then((data) => {
        setRecommendations(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [telemetry?.operating_mode, telemetry?.temperature]);

  const handleSimulateAction = (rec: Recommendation) => {
    navigate('/mission-control/simulation', {
      state: { prefill: rec.simulation_parameters, title: rec.title }
    });
  };

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'HIGH':
        return 'bg-rose-950 text-rose-300 border-rose-800 shadow-[0_0_8px_rgba(244,63,94,0.4)] animate-pulse';
      case 'MEDIUM':
        return 'bg-amber-950 text-amber-300 border-amber-800 shadow-[0_0_8px_rgba(245,158,11,0.3)]';
      default:
        return 'bg-emerald-950 text-emerald-300 border-emerald-800';
    }
  };

  return (
    <div className="space-y-6">
      {/* Title Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#16243f]/80 pb-3.5">
        <div>
          <h1 className="text-xl font-display font-bold text-slate-100 flex items-center gap-2.5">
            <LifeBuoy className="w-5 h-5 text-cyan-400" />
            OPERATIONAL RECOMMENDATIONS & ACTION PLANS
          </h1>
          <p className="text-xs text-slate-400 telemetry-mono mt-0.5">
            AI and rule-based mitigation strategies engineered to avert predicted failures and restore nominal health.
          </p>
        </div>

        <div className="text-xs telemetry-mono text-slate-400 bg-[#071328]/90 px-3.5 py-1.5 rounded-md border border-[#16243f] shadow-sm">
          ACTIONS AVAILABLE: <strong className="text-cyan-300 font-bold">{recommendations.length}</strong>
        </div>
      </div>

      {/* Safety Notice */}
      <div className="p-4 rounded-xl bg-[#0a1628]/90 border border-cyan-900/60 flex items-center gap-3.5 text-xs telemetry-mono text-cyan-300 shadow-sm">
        <ShieldCheck className="w-6 h-6 text-cyan-400 shrink-0" />
        <div className="font-sans leading-relaxed text-slate-300 text-xs">
          <strong className="text-cyan-300 font-mono">Safety & Operational Protocol:</strong> Recommendations generated by ORBITAL TWIN are intended for engineering simulation and verification. Actions are validated through counterfactual simulation before ground commands are committed.
        </div>
      </div>

      {/* Recommendation Action Cards Feed */}
      <div className="space-y-4">
        {recommendations.map((rec) => {
          const isHigh = rec.priority === 'HIGH';
          return (
            <div
              key={rec.id}
              className={`hud-panel hud-corner p-5 rounded-xl border transition-all ${
                isHigh
                  ? 'border-amber-500/60 bg-amber-950/20 shadow-[0_0_16px_rgba(245,158,11,0.2)]'
                  : 'border-[#16243f] hover:border-cyan-500/40'
              }`}
            >
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                <div className="space-y-2.5 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="telemetry-mono text-xs text-slate-400 font-bold">{rec.id}</span>
                    <span className="text-xs telemetry-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800/50">
                      {rec.subsystem.toUpperCase()} SUBSYSTEM
                    </span>
                    <span className={`text-[10px] telemetry-mono font-bold px-2 py-0.5 rounded border ${getPriorityBadge(rec.priority)}`}>
                      {rec.priority} PRIORITY
                    </span>
                  </div>

                  <h3 className="text-base font-hud font-bold text-slate-100 tracking-wide">{rec.title}</h3>
                  <p className="text-xs text-slate-300 leading-relaxed font-sans">{rec.description}</p>

                  <div className="p-3 rounded-lg bg-[#071120]/90 border border-emerald-900/50 text-xs telemetry-mono text-emerald-400 flex items-center gap-2 mt-2">
                    <CheckCircle2 className="w-4 h-4 shrink-0 shadow-[0_0_6px_#34d399]" />
                    <span className="font-sans text-xs text-emerald-300">
                      <strong>Projected Outcome:</strong> {rec.simulated_effect}
                    </span>
                  </div>
                </div>

                {/* Simulate Action Button */}
                <div className="shrink-0 flex flex-col justify-center items-end border-t md:border-t-0 border-[#16243f] pt-3 md:pt-0">
                  <button
                    onClick={() => handleSimulateAction(rec)}
                    className="px-4 py-2.5 rounded-lg bg-gradient-to-r from-cyan-600 to-cyan-500 hover:from-cyan-500 hover:to-cyan-400 text-white text-xs font-hud font-bold tracking-widest uppercase flex items-center gap-2 transition-all shadow-[0_0_16px_rgba(0,240,255,0.4)] cursor-pointer"
                  >
                    <Sliders className="w-4 h-4" />
                    SIMULATE ACTION
                  </button>
                  <span className="text-[10px] telemetry-mono text-slate-500 mt-1.5">
                    Pre-fills What-If Simulator
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
